// generated by Typeconf, DO NOT EDIT
import fs from 'fs';

export * from './all.js' // Your config types
export { default as new-serviceConfig } from '../new-service.config.js'
export { default as old-serviceConfig } from '../old-service.config.js'
