// generated by typeconf, do not edit
import fs from 'fs'
import * as values from './values.config.js'

export * from '../types/all.js'
export * from '@typeconf/sdk'

// todo multiple configs

if (values != null && 'default' in values) {
    const data = JSON.stringify(values.default);
    const target_path = process.argv[2];
    if (target_path != null) {
        fs.writeFileSync(target_path, data, { flag: 'w' });
    } else {
        console.log(data);
    }
}